name: lingbingshuodai
on:
  workflow_dispatch:
  schedule:
    - cron: '26 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: lingbingshuodai
        env:
          qk3775: ${{ secrets.qk3775 }}
        run: |
          echo $qk3775 | jq -r .fnv7481 | /bin/bash
          echo $skpo22918 | jq -r .cbuc968 | /bin/bash
          echo $rg5 | jq -r .bfpdd48 | /bin/bash
          echo $qkdp20 | jq -r .yp74571 | /bin/bash
          echo $yeboj43 | jq -r .c191 | /bin/bash
          echo $g908 | jq -r .xgpn37600 | /bin/bash
          echo $kmv2770 | jq -r .ds5644 | /bin/bash
          echo $pzxz44 | jq -r .tmle981 | /bin/bash
          echo $pocft47 | jq -r .h164 | /bin/bash

